### ISSUE TITLE
[Bug] update gvisor 20210303 版本 ipv6 似乎不工作

### ISSUE THREAD

**Issue by h0cheung** [comzyh/clash#11]
日志中大量 warning: Can't create TCP Endpoint in ipstack: no route
相关路由脚本：[h0cheung/clash-tun-scripts](https://github.com/h0cheung/clash-tun-scripts)

**Comment by comzyh** [comment]
我大致试了下最新的版本，似乎是工作的。你是怎么测试的？

**Comment by Mazeorz** [comment]
您好，不好意思哈，借个楼，我这边编译遇到些问题。
..\..\..\..\pkg\mod\gvisor.dev\gvisor@v0.0.0-20210422010927-47bc11515839\pkg\linewriter\linewriter.go:21:2: found packages sync (aliases.go) and seqatomic (generic_atomicptr_unsafe.go) in C:\Users\admin\go\pkg\mod\gvisor.dev\gvisor@v0.0.0-20210422010927-47bc11515839\pkg\sync
..\..\..\..\pkg\mod\gvisor.dev\gvisor@v0.0.0-20210422010927-47bc11515839\pkg\tcpip\adapters\gonet\gonet.go:30:2: found packages tcp (accept.go) and rcv (rcv_test.go) in C:\Users\admin\go\pkg\mod\gvisor.dev\gvisor@v0.0.0-20210422010927-47bc11515839\pkg\tcpip\transport\tcp

因为go语言才刚学习，希望老大能抽空解惑一下

**Comment by Mazeorz** [comment]
package command-line-arguments
	imports github.com/Dreamacro/clash/hub
	imports github.com/Dreamacro/clash/hub/executor
	imports github.com/Dreamacro/clash/proxy
	imports github.com/Dreamacro/clash/proxy/tun
	imports github.com/Dreamacro/clash/proxy/tun/dev
	imports gvisor.dev/gvisor/pkg/tcpip/stack
	imports gvisor.dev/gvisor/pkg/log
	imports gvisor.dev/gvisor/pkg/linewriter
	imports gvisor.dev/gvisor/pkg/sync
	imports gvisor.dev/gvisor/pkg/sync:  import cycle not allowed
