### ISSUE TITLE
能否在open tun 之后自动添加路由表呢？

### ISSUE THREAD

**Issue by josh-chan** [comzyh/clash#6]
RT, 默认添加 Fake-IP 的网关，可选添加其它网段，如
sudo route -n add -net 1 198.18.0.1
sudo route -n add -net 2/7 198.18.0.1
sudo route -n add -net 4/6 198.18.0.1
sudo route -n add -net 8/5 198.18.0.1
sudo route -n add -net 16/4 198.18.0.1
sudo route -n add -net 32/3 198.18.0.1
sudo route -n add -net 64/2 198.18.0.1
sudo route -n add -net 128.0/1 198.18.0.1

**Comment by comzyh** [comment]
没有计划，添加路由表的方法很多，选择困难。在clashw外面用脚本添加也挺方便的。
